using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace GwyfJpn.Core;

 [DataContract]
/// <summary>
/// Root JSON document loaded by the BepInEx plugin and generated by the extractor.
/// Extracted files may omit optional translator hints; the runtime only requires id/source/ja.
/// </summary>
public sealed class TranslationDocument
{
    [DataMember(Name = "schemaVersion", Order = 0)]
    public int SchemaVersion { get; set; } = 1;

    [DataMember(Name = "entries", Order = 1)]
    public List<TranslationEntry> Entries { get; set; } = new();
}

 [DataContract]
/// <summary>
/// One translatable string. Usage is intentionally optional and manually curated;
/// the extractor must not invent usage/style labels because that creates false context.
/// </summary>
public sealed class TranslationEntry
{
    [DataMember(Name = "id", Order = 0)]
    public string Id { get; set; } = string.Empty;

    [DataMember(Name = "source", Order = 1)]
    public string Source { get; set; } = string.Empty;

    [DataMember(Name = "ja", Order = 2)]
    public string Ja { get; set; } = string.Empty;

    [DataMember(Name = "usage", Order = 3, EmitDefaultValue = false)]
    public string? Usage { get; set; }

    [DataMember(Name = "context", Order = 4, EmitDefaultValue = false)]
    public TranslationContext? Context { get; set; }

    [DataMember(Name = "fontScale", Order = 5, EmitDefaultValue = false)]
    public float? FontScale { get; set; }

    [DataMember(Name = "textColor", Order = 6, EmitDefaultValue = false)]
    public string? TextColor { get; set; }

    [DataMember(Name = "outlineColor", Order = 7, EmitDefaultValue = false)]
    public string? OutlineColor { get; set; }

    [DataMember(Name = "outlineWidth", Order = 8, EmitDefaultValue = false)]
    public float? OutlineWidth { get; set; }

    [DataMember(Name = "fontWeight", Order = 9, EmitDefaultValue = false)]
    public string? FontWeight { get; set; }
}

 [DataContract]
/// <summary>
/// Evidence for where a string was found. This is review context, not a translation key.
/// Runtime replacement still prefers the stable id and then falls back to source matching.
/// </summary>
public sealed class TranslationContext
{
    [DataMember(Name = "file", Order = 0, EmitDefaultValue = false)]
    public string? File { get; set; }

    [DataMember(Name = "pathId", Order = 1, EmitDefaultValue = false)]
    public long? PathId { get; set; }

    [DataMember(Name = "classId", Order = 2, EmitDefaultValue = false)]
    public int? ClassId { get; set; }

    [DataMember(Name = "stringOffset", Order = 3, EmitDefaultValue = false)]
    public int? StringOffset { get; set; }

    [DataMember(Name = "gameObject", Order = 4, EmitDefaultValue = false)]
    public string? GameObject { get; set; }

    [DataMember(Name = "script", Order = 5, EmitDefaultValue = false)]
    public string? Script { get; set; }

    [DataMember(Name = "method", Order = 6, EmitDefaultValue = false)]
    public string? Method { get; set; }

    [DataMember(Name = "type", Order = 7, EmitDefaultValue = false)]
    public string? Type { get; set; }

    [DataMember(Name = "field", Order = 8, EmitDefaultValue = false)]
    public string? Field { get; set; }

    [DataMember(Name = "fieldType", Order = 9, EmitDefaultValue = false)]
    public string? FieldType { get; set; }
}

/// <summary>
/// Result of a translation lookup. MatchedId is recorded for diagnostics and future logging.
/// </summary>
public sealed class ReplacementResult
{
    public ReplacementResult(
        string source,
        string output,
        bool replaced,
        string? matchedId,
        float? fontScale = null,
        TranslationTextStyle? textStyle = null)
    {
        Source = source;
        Output = output;
        Replaced = replaced;
        MatchedId = matchedId;
        FontScale = fontScale;
        TextStyle = textStyle;
    }

    public string Source { get; }
    public string Output { get; }
    public bool Replaced { get; }
    public string? MatchedId { get; }
    public float? FontScale { get; }
    public TranslationTextStyle? TextStyle { get; }
}

/// <summary>
/// Optional TMP visual style carried by a translation entry.
/// Values are kept as serialized strings/numbers so the core project stays Unity-free.
/// </summary>
public sealed class TranslationTextStyle
{
    public TranslationTextStyle(string? textColor, string? outlineColor, float? outlineWidth, string? fontWeight)
    {
        TextColor = textColor;
        OutlineColor = outlineColor;
        OutlineWidth = outlineWidth;
        FontWeight = fontWeight;
    }

    public string? TextColor { get; }
    public string? OutlineColor { get; }
    public float? OutlineWidth { get; }
    public string? FontWeight { get; }
}
